# Copyright 2023 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: "gcr.io/cloud-builders/wget"
    script: |
      wget -O ko.tar.gz "https://github.com/ko-build/ko/releases/download/v${VERSION}/ko_${VERSION}_Linux_x86_64.tar.gz"
      tar xf ko.tar.gz
    env:
      - "VERSION=0.14.1"
  - name: "golang:1.21.0-bookworm"
    script: |
      cd forwarder
      echo $(/workspace/ko build .) > /workspace/forwarder-container.txt || exit 1
    env:
      - KO_DOCKER_REPO=asia-east1-docker.pkg.dev/yoshifumi-demo/demo-container

  - name: "ubuntu"
    script: |
      cat /workspace/forwarder-container.txt

options:
  substitution_option: "ALLOW_LOOSE"
  logging: CLOUD_LOGGING_ONLY

serviceAccount: "projects/yoshifumi-demo/serviceAccounts/terraform@yoshifumi-demo.iam.gserviceaccount.com"
